package com.tangluck.common.api;

public enum ErrorCode {
    REGION_BLOCKED,
    AGE_NOT_ALLOWED,
    CONSENT_REQUIRED,
    EMAIL_EXISTS,
    AUTH_INVALID_CREDENTIALS,
    CLAIM_DUPLICATED,
    CAMPAIGN_NOT_ACTIVE,
    BUDGET_EXHAUSTED,
    SC_POLICY_BLOCKED,
    LEGAL_APPROVAL_REQUIRED,
    PAYMENT_NOT_ALLOWED,
    KYC_REQUIRED,
    REDEMPTION_NOT_ALLOWED,
    RISK_REVIEW_REQUIRED,
    IDEMPOTENCY_CONFLICT,
    VALIDATION_FAILED,
    INTERNAL_ERROR
}
